### ISSUE TITLE
Fix meta tags and favicon

### ISSUE THREAD

**Issue by pfletcherhill** [hillstreetlabs/parr-web#7]
- [ ] Favicon is not the right logo and weirdly pixelated
- [ ] Add image so it shows up in slack or twitter when shared
- [ ] Maybe expand the description to make it more useful
